export enum MessageCodes {
  /*  HTTP RESPONSE CODES*/
  HTTP_RESPONSE_CODE_OK = 'HTTP_RESPONSE_CODE_OK',
  HTTP_RESPONSE_CODE_NOT_FOUND = 'HTTP_RESPONSE_CODE_NOT_FOUND',
  HTTP_RESPONSE_CODE_UNAUTHORIZED = 'HTTP_RESPONSE_CODE_UNAUTHORIZED',
  HTTP_RESPONSE_CODE_INTERNAL_SERVER_ERROR = 'HTTP_RESPONSE_CODE_INTERNAL_SERVER_ERROR',

  /* EPRICER MESSAGE CODES */
  TL_TECHNICAL_ERROR = 'ET_000',
  TL_USER_NOT_FOUND = 'EF_0001'
}
